version: "3"
services:
  postgres:
    image: "postgres:latest"

    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=content_bin
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
